meta:
  model_name: vit_small
  use_bfloat16: true
  use_fused_attention: true
  checkpoint: logs/test_small/jepa-latest.pth.tar
eval:
  batch_size: 256
  num_workers: 4
  epochs: 50
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0
data:
  crop_size: 224
mask:
  patch_size: 14
logging:
  folder: logs/eval_linear/
